/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Product {
    id: bigint;
    name: string;
    isSale: boolean;
    imageUrl: string;
    category: ProductCategory;
    salePrice?: number;
    rating: number;
    isNew: boolean;
    price: number;
}
export enum ProductCategory {
    men = "men",
    accessories = "accessories",
    women = "women"
}
export interface backendInterface {
    addToCart(productId: bigint, quantity: bigint): Promise<void>;
    clearCart(): Promise<void>;
    getAllProducts(): Promise<Array<Product>>;
    getCart(): Promise<Array<[Product, bigint]>>;
    getProductsByCategory(category: ProductCategory): Promise<Array<Product>>;
    getWishlist(): Promise<Array<Product>>;
    removeFromCart(productId: bigint): Promise<void>;
    toggleWishlist(productId: bigint): Promise<boolean>;
}
import type { Product as _Product, ProductCategory as _ProductCategory } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addToCart(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0, arg1);
            return result;
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<Array<[Product, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: ProductCategory): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(to_candid_ProductCategory_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(to_candid_ProductCategory_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWishlist(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWishlist();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWishlist();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromCart(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0);
            return result;
        }
    }
    async toggleWishlist(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleWishlist(arg0);
            return result;
        }
    }
}
function from_candid_ProductCategory_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    isSale: boolean;
    imageUrl: string;
    category: _ProductCategory;
    salePrice: [] | [number];
    rating: number;
    isNew: boolean;
    price: number;
}): {
    id: bigint;
    name: string;
    isSale: boolean;
    imageUrl: string;
    category: ProductCategory;
    salePrice?: number;
    rating: number;
    isNew: boolean;
    price: number;
} {
    return {
        id: value.id,
        name: value.name,
        isSale: value.isSale,
        imageUrl: value.imageUrl,
        category: from_candid_ProductCategory_n4(_uploadFile, _downloadFile, value.category),
        salePrice: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.salePrice)),
        rating: value.rating,
        isNew: value.isNew,
        price: value.price
    };
}
function from_candid_tuple_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Product, bigint]): [Product, bigint] {
    return [
        from_candid_Product_n2(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    men: null;
} | {
    accessories: null;
} | {
    women: null;
}): ProductCategory {
    return "men" in value ? ProductCategory.men : "accessories" in value ? ProductCategory.accessories : "women" in value ? ProductCategory.women : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Product, bigint]>): Array<[Product, bigint]> {
    return value.map((x)=>from_candid_tuple_n8(_uploadFile, _downloadFile, x));
}
function to_candid_ProductCategory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): _ProductCategory {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): {
    men: null;
} | {
    accessories: null;
} | {
    women: null;
} {
    return value == ProductCategory.men ? {
        men: null
    } : value == ProductCategory.accessories ? {
        accessories: null
    } : value == ProductCategory.women ? {
        women: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
